version: '2'

services:
  dynamo:
    image: deangiberson/aws-dynamodb-local
    expose:
      - "8000"
    ports:
      - "8000:8000"
  rom:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: rspec
    environment:
      - DYNAMO_ENDPOINT=http://dynamo:8000
      - CI
    volumes:
      - .:/app
    links:
      - dynamo
