version: "3.9"

services:
  dynamodb:
    image: "amazon/dynamodb-local"
    ports:
      - "8000:8000"
  rom:
    build:
      context: .
      dockerfile: Dockerfile
    command: rspec
    environment:
      - DYNAMO_ENDPOINT=http://dynamo:8000
      - CI
